<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Fix qr_umum_token and qr_token columns to use TEXT instead of VARCHAR(255).
 * Signed URLs generated by Laravel's URL::temporarySignedRoute() can exceed 255 characters.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Drop the unique index on qr_umum_token before changing type (PostgreSQL requires this)
        if (DB::getDriverName() !== 'sqlite') {
            DB::statement('DROP INDEX IF EXISTS idx_qr_umum_token_unique');
            DB::statement('DROP INDEX IF EXISTS idx_meeting_participants_qr_token');
        }

        Schema::table('meetings', function (Blueprint $table) {
            $table->text('qr_umum_token')->nullable()->change();
        });

        Schema::table('meeting_participants', function (Blueprint $table) {
            $table->text('qr_token')->nullable()->change();
        });
    }

    public function down(): void
    {
        Schema::table('meetings', function (Blueprint $table) {
            $table->string('qr_umum_token', 255)->nullable()->change();
        });

        Schema::table('meeting_participants', function (Blueprint $table) {
            $table->string('qr_token', 255)->nullable()->change();
        });
    }
};
